services:
  # Production mode
  app:
    build:
      context: .
      args:
        NODE_ENV: production
    container_name: nextjs-app
    restart: unless-stopped
    ports:
      - "3004:3000"
    environment:
      - NODE_ENV=production

    networks:
      - web_network

    labels:
      - traefik.enable=true
      - traefik.docker.network=web_network

      - traefik.http.routers.nextapp.entrypoints=http
      - traefik.http.routers.nextapp.rule=Host(`next.yopaz-demo.dev`)
      - traefik.http.routers.nextapp.service=nextapp
      - traefik.http.services.nextapp.loadbalancer.server.port=3000

  # Development mode (hot reload)
  dev:
    build:
      context: .
      args:
        NODE_ENV: development
    container_name: nextjs-dev
    restart: unless-stopped
    ports:
      - "3005:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    profiles:
      - dev

networks:
  web_network:
    external: true